spring.datasource:
  type: com.zaxxer.hikari.HikariDataSource
  jdbcUrl: jdbc:mysql://localhost:3306/test
  username: root
  password: wuketao277
  driverClassName: com.mysql.jdbc.Driver
  #配置数据库连接池HikariCP
  maximum-pool-size: 50
  maximum-idle: 50
  minimum-idle: 20

spring.jpa:
  database: mysql
  show-sql: true
  hibernate.ddl-auto: update
  hibernate.naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
  properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
